# Generated by Django 4.2.4 on 2024-12-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='images',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
