# Generated by Django 4.2.4 on 2024-12-18 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='options',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.variation'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product'),
        ),
        migrations.DeleteModel(
            name='VariationOption',
        ),
    ]
