# Generated by Django 5.2.2 on 2025-06-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage_variation_productdescription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
