# Generated by Django 5.2.2 on 2025-06-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_category_category_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title', 'parent')},
        ),
    ]
