# Generated by Django 5.2.2 on 2025-06-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_category_parent_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/category_cover/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='titl', max_length=128, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
