# Generated by Django 5.2.2 on 2025-06-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_category_cover_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='images/brand_cover/', verbose_name='تصویر'),
        ),
    ]
