# Generated by Django 4.2.4 on 2024-01-10 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_order_shipping_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
                ('code', models.CharField(max_length=256, null=True)),
                ('percent', models.CharField(max_length=256, null=True)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2024, 1, 11, 5, 56, 9, 154693), null=True)),
            ],
        ),
    ]
