# Generated by Django 4.2.4 on 2024-01-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_offcode_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcode',
            name='expiration_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
