# Generated by Django 4.2.4 on 2024-01-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_offcode_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
                ('code', models.CharField(max_length=256, null=True)),
                ('percent', models.CharField(max_length=256, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OffCode',
        ),
    ]
