# Generated by Django 4.2.4 on 2024-01-15 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_productgroup_slug'),
        ('cart', '0007_discountcode_delete_offcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.producttype'),
        ),
    ]
