# Generated by Django 4.2.4 on 2024-01-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_order_shipping_address_delete_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.discountcode'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='percent',
            field=models.IntegerField(max_length=16, null=True),
        ),
    ]
