# Generated by Django 4.2.4 on 2024-01-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cart_discount_alter_discountcode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='percent',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
