# Generated by Django 4.2.4 on 2024-01-21 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_shippingaddress_address_compact_and_more'),
        ('cart', '0011_alter_discountcode_percent_alter_discountcode_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.shippingaddress'),
        ),
    ]
