# Generated by Django 4.2.4 on 2024-01-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_cart_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_method',
            field=models.CharField(choices=[('normal', 30000), ('special', 80000)], default='normal', max_length=64),
        ),
    ]






