# Generated by Django 4.2.4 on 2024-01-21 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_shippingaddress_address_compact_and_more'),
        ('cart', '0014_alter_cart_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.shippingaddress'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.discountcode'),
        ),
    ]
