# Generated by Django 4.2.4 on 2024-01-22 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_cart_address_alter_cart_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='address',
            new_name='shipping_address',
        ),
    ]
