# Generated by Django 4.2.4 on 2024-01-05 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otprequest_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('request_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=6, null=True)),
                ('valid_until', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'One Time Password',
                'verbose_name_plural': 'One Time Passwords',
            },
        ),
        migrations.DeleteModel(
            name='OtpRequest',
        ),
    ]
