# Generated by Django 4.2.4 on 2024-01-20 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_request_id_otp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
