# Generated by Django 4.2.4 on 2024-01-20 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_otp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('address_compact', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('district', models.CharField(blank=True, max_length=128, null=True)),
                ('last', models.CharField(blank=True, max_length=64, null=True)),
                ('latitude', models.CharField(blank=True, max_length=32, null=True)),
                ('longitude', models.CharField(blank=True, max_length=32, null=True)),
                ('neighbourhood', models.CharField(blank=True, max_length=32, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('plaque', models.CharField(blank=True, max_length=16, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=64, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=32, null=True)),
                ('primary', models.CharField(blank=True, max_length=64, null=True)),
                ('province', models.CharField(blank=True, max_length=32, null=True)),
                ('region', models.CharField(blank=True, max_length=32, null=True)),
                ('rural_district', models.CharField(blank=True, max_length=64, null=True)),
                ('stairs', models.CharField(blank=True, max_length=32, null=True)),
                ('village', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
