# Generated by Django 4.2.4 on 2024-01-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_compact',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='district',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='neighbourhood',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='postal_address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='primary',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='rural_district',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='village',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='province',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
