# Generated by Django 4.2.4 on 2024-01-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_productgroup_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/banner_cover'),
        ),
        migrations.AddField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
