# Generated by Django 4.2.4 on 2024-04-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_banner_cover_banner_created_at_banner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
